### ISSUE TITLE
Eliminar Paquete

### ISSUE THREAD

**Issue by andres-arana** [andres-arana/degree-7552-tp#42]
Siendo un usuario, quiero poder eliminar un paquete completo para poder mantener actualizado el modelo.
- El usuario selecciona un paquete a eliminar desde el explorador del proyecto haciendo un click en él.
- El usuario presiona el botón "Eliminar". El botón debe deshabilitarse si el paquete es el paquete raíz del proyecto.
- El sistema despliega un diálogo pidiendo confirmación de la acción a realizar.
- El usuario confirma la acción y el sistema elimina el paquete del modelo, quitándolo del explorador de proyecto.

**Comment by juanimarchese** [comment]
Listo
