### ISSUE TITLE
Agregar Estado en Diagrama de Comportamiento

### ISSUE THREAD

**Issue by andres-arana** [andres-arana/degree-7552-tp#45]
Siendo un usuario, quiero poder agregar un nuevo estado en el diagrama de comportamiento para modelar una interfase de usuario en el sistema modelado.
- El usuario utiliza la paleta de herramientas para seleccionar una de las herramientas "Formulario de Entrada", "Formulario de Salida" o "Formulario Compuesto".
- El usuario hace click en un punto del diagrama de comportamiento.
- El sistema crea un nuevo estado en el diagrama con un nombre correlativo "Estado N", ubicado en la posición clickeada en el paso anterior, con el tipo correspondiente a la herramienta seleccionada.

**Comment by juanimarchese** [comment]
Ya esta hecho
